language: csharp
solution: LastMinuteBack.sln
install:
  - nuget restore LastMinuteBack.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release LastMinuteBack.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./UnitTests/bin/Release/UnitTests.dll